name: Build

on:
  pull_request:
    branches:
      - uat
      - main
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
