name: Lint

on:
  pull_request:
    branches:
      - uat
      - main
      - 'release/**'
      - 'hotfix/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
